ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'
  auth:
    jwtSecret: 'c3b126a8dc2da887d3b2def89c296198c28289f60e82c1b433c775e5abc1c3ba'
    jwtExpirationMs: 14400000

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
